### ISSUE TITLE
Job Location

### ISSUE THREAD

**Issue by clickanidea** [polyspastos/indeed_scraper#1]
Thanks for the nice work, would it be possible to add the job location ?

**Comment by polyspastos** [comment]
hey, thanks! it is available through the "--city" argument, e.g. --city Hannover. or do you mean some sort of triangulation based on gps coordinates? please elaborate

**Comment by polyspastos** [comment]
thanks, glad i could help! sure, i will take a look at it on Saturday

**Comment by clickanidea** [comment]
I was thinking in secondary_process to add a 'location' field (besides title, summary, etc)

**Comment by polyspastos** [comment]
yes, in the meantime ive figured it out, this is why ive deleted my comment :)

**Comment by polyspastos** [comment]
done, sorry for being late, yesterday was quite hectic

**Comment by clickanidea** [comment]
Thanks !

**Comment by polyspastos** [comment]
np, thanks for pointing it out!
